/*
 * dc_gen.c — 7 output generators for device config packages
 *
 * Generates: PIN_MAP, .map, .lvl, .tim, .tp, PowerOn.sh, PowerOff.sh
 * PIN_MAP bridges to Pipeline 1 — pc_load_pinmap() reads it directly.
 */

#include "dc.h"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>

/* ═══════════════════════════════════════════════════════════════
 * HELPERS
 * ═══════════════════════════════════════════════════════════════ */

static void build_path(char *buf, int max, const char *dir, const char *file)
{
    if (dir && *dir) {
        int len = (int)strlen(dir);
        if (dir[len - 1] == '/' || dir[len - 1] == '\\')
            snprintf(buf, max, "%s%s", dir, file);
        else
            snprintf(buf, max, "%s/%s", dir, file);
    } else {
        snprintf(buf, max, "%s", file);
    }
}

static const char *dir_str(int direction)
{
    switch (direction) {
    case 1:  return "I";
    case 2:  return "O";
    default: return "IO";
    }
}

/* Find bank name for a channel */
static const char *find_bank(const DcTesterProfile *prof, int channel)
{
    for (int i = 0; i < prof->num_banks; i++) {
        const DcGpioBank *b = &prof->banks[i];
        if (channel >= b->start_pin && channel < b->start_pin + b->num_pins)
            return b->name;
    }
    return "UNKNOWN";
}

/* Find bank index for a channel */
static int find_bank_idx(const DcTesterProfile *prof, int channel)
{
    for (int i = 0; i < prof->num_banks; i++) {
        const DcGpioBank *b = &prof->banks[i];
        if (channel >= b->start_pin && channel < b->start_pin + b->num_pins)
            return i;
    }
    return -1;
}

/* Find core hardware by name */
static const DcCoreHw *find_core(const DcTesterProfile *prof, const char *name)
{
    for (int i = 0; i < prof->num_cores; i++) {
        if (strcmp(prof->cores[i].name, name) == 0)
            return &prof->cores[i];
    }
    return NULL;
}

/* ═══════════════════════════════════════════════════════════════
 * VALIDATION
 * ═══════════════════════════════════════════════════════════════ */

int dc_validate_device(const DcTesterProfile *prof, const DcDeviceIR *dev,
                       char *errmsg, int errmax)
{
    /* Check channel bounds */
    for (int i = 0; i < dev->num_channels; i++) {
        if (dev->channels[i].channel < 0 ||
            dev->channels[i].channel >= prof->total_channels) {
            snprintf(errmsg, errmax,
                "Channel %d out of range [0, %d) for signal '%s'",
                dev->channels[i].channel, prof->total_channels,
                dev->channels[i].signal_name);
            return DC_ERR_VALIDATE;
        }
    }

    /* Check supply core names exist in profile */
    for (int i = 0; i < dev->num_supplies; i++) {
        if (!find_core(prof, dev->supplies[i].core_name)) {
            snprintf(errmsg, errmax,
                "Unknown core '%s' — not in profile '%s'",
                dev->supplies[i].core_name, prof->name);
            return DC_ERR_VALIDATE;
        }
    }

    /* Check for duplicate channels */
    for (int i = 0; i < dev->num_channels; i++) {
        for (int j = i + 1; j < dev->num_channels; j++) {
            if (dev->channels[i].channel == dev->channels[j].channel) {
                snprintf(errmsg, errmax,
                    "Duplicate channel %d: '%s' and '%s'",
                    dev->channels[i].channel,
                    dev->channels[i].signal_name,
                    dev->channels[j].signal_name);
                return DC_ERR_VALIDATE;
            }
        }
    }

    return DC_OK;
}

/* ═══════════════════════════════════════════════════════════════
 * 1. PIN_MAP — signal_name channel direction (per line)
 *
 * Format compatible with pc_load_pinmap() Format 2:
 *   channel signal_name
 * ═══════════════════════════════════════════════════════════════ */

int dc_gen_pinmap(const DcTesterProfile *prof, const DcDeviceIR *dev,
                  const char *output_dir)
{
    (void)prof;
    char path[512];
    build_path(path, sizeof(path), output_dir, "PIN_MAP");

    FILE *f = fopen(path, "w");
    if (!f) return DC_ERR_WRITE;

    fprintf(f, "# PIN_MAP for %s\n", dev->device_name);
    fprintf(f, "# Generated by pattern_converter device config generator\n");
    fprintf(f, "# Format: GPIO_INDEX SIGNAL_NAME\n");

    for (int i = 0; i < dev->num_channels; i++) {
        const DcChannelMap *ch = &dev->channels[i];
        fprintf(f, "%d %s\n", ch->channel, ch->signal_name);
    }

    fclose(f);
    return DC_OK;
}

/* ═══════════════════════════════════════════════════════════════
 * 2. .map — signal_name = gpio_N (per line)
 * ═══════════════════════════════════════════════════════════════ */

int dc_gen_map(const DcTesterProfile *prof, const DcDeviceIR *dev,
               const char *output_dir)
{
    char filename[DC_MAX_NAME];
    snprintf(filename, sizeof(filename), "%s.map", dev->device_name);
    char path[512];
    build_path(path, sizeof(path), output_dir, filename);

    FILE *f = fopen(path, "w");
    if (!f) return DC_ERR_WRITE;

    fprintf(f, "# Signal Map: %s\n", dev->device_name);
    fprintf(f, "# Tester: %s (%d channels)\n", prof->name, prof->total_channels);
    fprintf(f, "#\n");

    for (int i = 0; i < dev->num_channels; i++) {
        const DcChannelMap *ch = &dev->channels[i];
        fprintf(f, "%s = %s_GPIO%d ; %s\n",
                ch->signal_name,
                find_bank(prof, ch->channel),
                ch->channel,
                dir_str(ch->direction));
    }

    fclose(f);
    return DC_OK;
}

/* ═══════════════════════════════════════════════════════════════
 * 3. .lvl — Bank voltages + VIH/VIL/VOH/VOL
 * ═══════════════════════════════════════════════════════════════ */

int dc_gen_lvl(const DcTesterProfile *prof, const DcDeviceIR *dev,
               const char *output_dir)
{
    char filename[DC_MAX_NAME];
    snprintf(filename, sizeof(filename), "%s.lvl", dev->device_name);
    char path[512];
    build_path(path, sizeof(path), output_dir, filename);

    FILE *f = fopen(path, "w");
    if (!f) return DC_ERR_WRITE;

    fprintf(f, "# Level Definitions: %s\n", dev->device_name);
    fprintf(f, "# Tester: %s\n", prof->name);
    fprintf(f, "#\n");
    fprintf(f, "# Bank Voltages\n");

    int n = dev->num_bank_voltages;
    if (n > prof->num_banks) n = prof->num_banks;
    for (int i = 0; i < n; i++) {
        fprintf(f, "BANK %s VOLTAGE=%.3f\n",
                prof->banks[i].name, dev->bank_voltages[i]);
    }

    fprintf(f, "#\n# Per-Signal Levels\n");

    for (int i = 0; i < dev->num_channels; i++) {
        const DcChannelMap *ch = &dev->channels[i];
        int bidx = find_bank_idx(prof, ch->channel);
        double v = (bidx >= 0 && bidx < n) ? dev->bank_voltages[bidx] : 1.8;

        /* Standard CMOS levels derived from bank voltage */
        double vih = v * 0.7;
        double vil = v * 0.3;
        double voh = v * 0.8;
        double vol = v * 0.2;

        fprintf(f, "%-20s VIH=%.3f VIL=%.3f VOH=%.3f VOL=%.3f\n",
                ch->signal_name, vih, vil, voh, vol);
    }

    fclose(f);
    return DC_OK;
}

/* ═══════════════════════════════════════════════════════════════
 * 4. .tim — Period + drive/compare edges
 * ═══════════════════════════════════════════════════════════════ */

int dc_gen_tim(const DcTesterProfile *prof, const DcDeviceIR *dev,
               const char *output_dir)
{
    char filename[DC_MAX_NAME];
    snprintf(filename, sizeof(filename), "%s.tim", dev->device_name);
    char path[512];
    build_path(path, sizeof(path), output_dir, filename);

    FILE *f = fopen(path, "w");
    if (!f) return DC_ERR_WRITE;

    /* Use device overrides if set, else profile defaults */
    double period  = dev->period_ns    > 0 ? dev->period_ns    : prof->default_period_ns;
    double drv_on  = dev->drive_on_ns  > 0 ? dev->drive_on_ns  : prof->default_drive_on_ns;
    double drv_off = dev->drive_off_ns > 0 ? dev->drive_off_ns : prof->default_drive_off_ns;
    double cmp     = dev->compare_ns   > 0 ? dev->compare_ns   : prof->default_compare_ns;

    fprintf(f, "# Timing Definitions: %s\n", dev->device_name);
    fprintf(f, "# Tester: %s\n", prof->name);
    fprintf(f, "#\n");
    fprintf(f, "PERIOD=%.1f\n", period);
    fprintf(f, "DRIVE_ON=%.1f\n", drv_on);
    fprintf(f, "DRIVE_OFF=%.1f\n", drv_off);
    fprintf(f, "COMPARE=%.1f\n", cmp);

    fclose(f);
    return DC_OK;
}

/* ═══════════════════════════════════════════════════════════════
 * 5. .tp — Test plan steps (pattern + loops)
 * ═══════════════════════════════════════════════════════════════ */

int dc_gen_tp(const DcTesterProfile *prof, const DcDeviceIR *dev,
              const char *output_dir)
{
    (void)prof;
    char filename[DC_MAX_NAME];
    snprintf(filename, sizeof(filename), "%s.tp", dev->device_name);
    char path[512];
    build_path(path, sizeof(path), output_dir, filename);

    FILE *f = fopen(path, "w");
    if (!f) return DC_ERR_WRITE;

    fprintf(f, "# Test Plan: %s\n", dev->device_name);
    fprintf(f, "# Steps: %d\n", dev->num_steps);
    fprintf(f, "#\n");
    fprintf(f, "# FORMAT: STEP PATTERN_NAME PATTERN_FILE LOOP_COUNT\n");

    for (int i = 0; i < dev->num_steps; i++) {
        const DcTestStep *ts = &dev->steps[i];
        fprintf(f, "%d %s %s %d\n",
                i + 1, ts->pattern_name, ts->pattern_file, ts->loop_count);
    }

    fclose(f);
    return DC_OK;
}

/* ═══════════════════════════════════════════════════════════════
 * 5b. plan.json — FBC TestPlanDef (DDR slots + autonomous execution)
 *
 * Outputs the JSON format consumed by host `set_test_plan()`.
 * Maps DcTestStep[] to TestPlanDef with slot assignments,
 * per-step temp/clock, fail actions, and duration.
 *
 * Steps with pattern_id == -1 get auto-assigned by step index (0-7).
 * Steps with temp_setpoint_dc == 0 get sentinel 0x7FFF (no change).
 * Steps with clock_div == -1 get sentinel 0xFF (no change).
 * ═══════════════════════════════════════════════════════════════ */

int dc_gen_plan_json(const DcTesterProfile *prof, const DcDeviceIR *dev,
                     const char *output_dir)
{
    (void)prof;
    if (dev->num_steps == 0 || dev->num_steps > 8) return DC_ERR_PARSE;

    char path[512];
    build_path(path, sizeof(path), output_dir, "plan.json");

    FILE *f = fopen(path, "w");
    if (!f) return DC_ERR_WRITE;

    /* Find loop_start: first step with loop_count > 1, or 0 */
    int loop_start = 0;
    for (int i = 0; i < dev->num_steps; i++) {
        if (dev->steps[i].loop_count > 1) {
            loop_start = i;
            break;
        }
    }

    /* Total duration: sum of all step durations (0 = single pass) */
    int total_duration = 0;
    for (int i = 0; i < dev->num_steps; i++) {
        total_duration += dev->steps[i].duration_secs;
    }

    fprintf(f, "{\n");
    fprintf(f, "  \"num_steps\": %d,\n", dev->num_steps);
    fprintf(f, "  \"loop_start\": %d,\n", loop_start);
    fprintf(f, "  \"total_duration_secs\": %d,\n", total_duration);
    fprintf(f, "  \"steps\": [\n");

    for (int i = 0; i < dev->num_steps; i++) {
        const DcTestStep *ts = &dev->steps[i];

        int slot = (ts->pattern_id >= 0) ? ts->pattern_id : i;
        int dur  = ts->duration_secs;
        const char *fail = (ts->fail_action == 1) ? "continue" : "abort";
        int thresh = ts->error_threshold;

        fprintf(f, "    {\n");
        fprintf(f, "      \"pattern_id\": %d,\n", slot);
        fprintf(f, "      \"duration_secs\": %d,\n", dur);
        fprintf(f, "      \"fail_action\": \"%s\",\n", fail);
        fprintf(f, "      \"error_threshold\": %d", thresh);

        /* Optional: temp_setpoint_dc (omit if 0 → defaults to 0x7FFF sentinel on host) */
        if (ts->temp_setpoint_dc != 0) {
            fprintf(f, ",\n      \"temp_setpoint_dc\": %d", ts->temp_setpoint_dc);
        }

        /* Optional: clock_div (omit if -1 → defaults to 0xFF sentinel on host) */
        if (ts->clock_div >= 0) {
            fprintf(f, ",\n      \"clock_div\": %d", ts->clock_div);
        }

        fprintf(f, "\n    }%s\n", (i < dev->num_steps - 1) ? "," : "");
    }

    fprintf(f, "  ]\n");
    fprintf(f, "}\n");

    fclose(f);
    return DC_OK;
}

/* ═══════════════════════════════════════════════════════════════
 * 6. PowerOn.sh — MIO enable + DAC set, ordered by sequence_order
 * ═══════════════════════════════════════════════════════════════ */

int dc_gen_power_on(const DcTesterProfile *prof, const DcDeviceIR *dev,
                    const char *output_dir)
{
    char path[512];
    build_path(path, sizeof(path), output_dir, "PowerOn.sh");

    FILE *f = fopen(path, "w");
    if (!f) return DC_ERR_WRITE;

    fprintf(f, "#!/bin/bash\n");
    fprintf(f, "# Power-On Sequence: %s\n", dev->device_name);
    fprintf(f, "# Auto-generated — do not edit\n\n");

    /* Sort supplies by sequence_order (simple insertion sort, max 16) */
    int order[DC_MAX_SUPPLIES];
    int n = dev->num_supplies;
    for (int i = 0; i < n; i++) order[i] = i;
    for (int i = 1; i < n; i++) {
        int key = order[i];
        int j = i - 1;
        while (j >= 0 && dev->supplies[order[j]].sequence_order >
                         dev->supplies[key].sequence_order) {
            order[j + 1] = order[j];
            j--;
        }
        order[j + 1] = key;
    }

    for (int i = 0; i < n; i++) {
        const DcSupplyAssign *s = &dev->supplies[order[i]];
        const DcCoreHw *hw = find_core(prof, s->core_name);
        if (!hw) continue;

        fprintf(f, "# Step %d: %s → %.3fV\n", s->sequence_order, s->core_name, s->voltage);
        fprintf(f, "echo %d > /sys/class/gpio/gpio%d/value  # Enable %s\n",
                1, hw->mio_pin, s->core_name);

        /* DAC value: 12-bit, 0-4095 maps to 0-2.5V (BU2505FV range) */
        int dac_val = (int)(s->voltage / 2.5 * 4095.0);
        if (dac_val > 4095) dac_val = 4095;
        if (dac_val < 0) dac_val = 0;
        fprintf(f, "dac_write %d %d  # Set %s to %.3fV\n",
                hw->dac_channel, dac_val, s->core_name, s->voltage);

        /* Ramp delay */
        if (s->ramp_delay_ms > 0) {
            int ms = (int)s->ramp_delay_ms;
            fprintf(f, "usleep %d  # Ramp delay\n", ms * 1000);
        }
        fprintf(f, "\n");
    }

    fprintf(f, "echo \"Power-on complete: %d supplies enabled\"\n", n);

    fclose(f);
    return DC_OK;
}

/* ═══════════════════════════════════════════════════════════════
 * 7. PowerOff.sh — Reverse of PowerOn
 * ═══════════════════════════════════════════════════════════════ */

int dc_gen_power_off(const DcTesterProfile *prof, const DcDeviceIR *dev,
                     const char *output_dir)
{
    char path[512];
    build_path(path, sizeof(path), output_dir, "PowerOff.sh");

    FILE *f = fopen(path, "w");
    if (!f) return DC_ERR_WRITE;

    fprintf(f, "#!/bin/bash\n");
    fprintf(f, "# Power-Off Sequence: %s\n", dev->device_name);
    fprintf(f, "# Auto-generated — do not edit\n\n");

    /* Sort supplies by sequence_order DESCENDING (reverse of power-on) */
    int order[DC_MAX_SUPPLIES];
    int n = dev->num_supplies;
    for (int i = 0; i < n; i++) order[i] = i;
    for (int i = 1; i < n; i++) {
        int key = order[i];
        int j = i - 1;
        while (j >= 0 && dev->supplies[order[j]].sequence_order <
                         dev->supplies[key].sequence_order) {
            order[j + 1] = order[j];
            j--;
        }
        order[j + 1] = key;
    }

    for (int i = 0; i < n; i++) {
        const DcSupplyAssign *s = &dev->supplies[order[i]];
        const DcCoreHw *hw = find_core(prof, s->core_name);
        if (!hw) continue;

        fprintf(f, "# Disable %s\n", s->core_name);
        fprintf(f, "dac_write %d 0  # Zero %s DAC\n",
                hw->dac_channel, s->core_name);
        fprintf(f, "echo 0 > /sys/class/gpio/gpio%d/value  # Disable %s\n",
                hw->mio_pin, s->core_name);
        if (s->ramp_delay_ms > 0) {
            int ms = (int)s->ramp_delay_ms;
            fprintf(f, "usleep %d  # Settle delay\n", ms * 1000);
        }
        fprintf(f, "\n");
    }

    fprintf(f, "echo \"Power-off complete: %d supplies disabled\"\n", n);

    fclose(f);
    return DC_OK;
}

/* ═══════════════════════════════════════════════════════════════
 * GENERATE ALL
 * ═══════════════════════════════════════════════════════════════ */

int dc_gen_all(const DcTesterProfile *prof, const DcDeviceIR *dev,
               const char *output_dir)
{
    int rc;
    if ((rc = dc_gen_pinmap(prof, dev, output_dir))    != DC_OK) return rc;
    if ((rc = dc_gen_map(prof, dev, output_dir))       != DC_OK) return rc;
    if ((rc = dc_gen_lvl(prof, dev, output_dir))       != DC_OK) return rc;
    if ((rc = dc_gen_tim(prof, dev, output_dir))       != DC_OK) return rc;
    if ((rc = dc_gen_tp(prof, dev, output_dir))        != DC_OK) return rc;
    if ((rc = dc_gen_plan_json(prof, dev, output_dir)) != DC_OK) return rc;
    if ((rc = dc_gen_power_on(prof, dev, output_dir))  != DC_OK) return rc;
    if ((rc = dc_gen_power_off(prof, dev, output_dir)) != DC_OK) return rc;
    return DC_OK;
}
